loadtester:
  targets:
    - name: serviceA
      url: https://api.example.com/v1/foo
      method: POST
      headers:
        Authorization: "Bearer SOME_TOKEN"
        Content-Type: "application/json"
      payloadPath: classpath:payloads/foo.json
      desiredTps: 300
      throttleIntervalMs: 0

    - name: serviceB
      url: https://api.example.com/v1/bar
      method: GET
      headers:
        Authorization: "Bearer OTHER_TOKEN"
      desiredTps: 50
      throttleIntervalMs: 10
