loadtester:
  targets:
    - name: serviceA
      url: https://dummyjson.com/auth/RESOURCE
      method: POST
      headers:
        Authorization: "Bearer SOME_TOKEN"
        Content-Type: "application/json"
      payloadPath: classpath:payloads/foo.json
      desiredTps: 300
      throttleIntervalMs: 10
